
-- USER DEFINED FUNCTIONS
 
-- user defined functions are block of statements which can be used whenever needed by the user,it is reusable.
-- input is needed, there is input parameters.a
-- output is called return value.


DELIMITER $$
CREATE FUNCTION SQUARE_NUM(NUM INT)
RETURNS INT
DETERMINISTIC
BEGIN 
 RETURN NUM*NUM ;
 END $$
 DELIMITER ;
 
 SELECT SQUARE_NUM(51) AS SQUAREOFFIVE;
 
 SELECT STRIKE_RATE,SQUARE_NUM(Strike_Rate) AS SQUARE_OF_STRIKE_RATE FROM PLAYERS;
 
 DELIMITER $$
CREATE FUNCTION DOUBLE_(NUM INT)
RETURNS INT
DETERMINISTIC
BEGIN 
 RETURN NUM*2 ;
 END $$
 DELIMITER ;
 
 SELECT DOUBLE_(51) AS DOUBLE_OF_FIVE; 
 
  DELIMITER $$
CREATE FUNCTION SUM_OF_NUM(NUM_1 INT,NUM_2 INT)
RETURNS INT
DETERMINISTIC
BEGIN 
 RETURN NUM_1 + NUM_2;
 END $$
 DELIMITER ;
 
 SELECT SUM_OF_NUM(51,23) AS SUM_OF_NUMBERS
 
  DELIMITER $$
CREATE FUNCTION DIV_OF_NUM(NUM_1 INT,NUM_2 INT)
RETURNS double
DETERMINISTIC
BEGIN 
 RETURN NUM_1 / NUM_2;
 END $$
 DELIMITER ;
 
 SELECT DIV_OF_NUM(51,9) AS DIV_OF_NUMBERS;